version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: minesweeper-postgres
    environment:
      POSTGRES_DB: minesweeperdb
      POSTGRES_USER: minesweeperuser
      POSTGRES_PASSWORD: minesweeperpassword
    ports:
      - "5432:5432"