version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: minesweeperdb
      POSTGRES_USER: minesweeperuser
      POSTGRES_PASSWORD: minesweeperpassword
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d


  # why is minesweeper-app included in here?
  # does the docker-compose contain both postgres AND rest api?
  minesweeper-app:
    image: minesweeper-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
