version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: minesweeperdb
      POSTGRES_USER: minesweeperuser
      POSTGRES_PASSWORD: minesweeperpassword
    ports:
      - "4646:4646"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

  minesweeper-app:
    image: minesweeper-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
